"""Simplified smooth/cliff clustering and visualization pipeline.

This file is a cleaned copy of smooth_ac.py with redundant comparison and
matrix-analysis utilities removed. It keeps:
- data loading
- standard cliff + smooth clustering
- exhaustive post-hoc smooth clustering
- molecule visualization compatible with cluster_data[<fp>_<threshold>]['smooth_ids']
- CSV export of summary statistics
"""

import os
import re
import sys
from collections import defaultdict

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from IPython.display import SVG, display
from rdkit import Chem
from rdkit.Chem import Draw

sys.path.append(os.path.join(os.path.dirname(__file__), ".."))
from bb_utils import bb_ac


def _increase_svg_font_size(svg_str, scale_factor=2.0):
    """Increase legend font sizes in an SVG generated by RDKit."""

    def scale_font(match):
        current_size = float(match.group(1))
        return f'font-size="{current_size * scale_factor}px"'

    return re.sub(r'font-size="([\d.]+)px"', scale_font, svg_str)


class FingerprintClusterAnalyzer:
    """Minimal analyzer for cliff/smooth clustering and molecule visualization."""

    def __init__(self, fingerprint_types=None, thresholds=None, top=10):
        self.fingerprint_types = fingerprint_types or ["ECFP", "MACCS", "RDKIT"]
        self.thresholds = thresholds if thresholds is not None else [0.95]
        self.top = top
        self.fingerprint_data = {}
        self.property_data = {}
        self.cluster_data = defaultdict(dict)
        self.results = []
        self.df_results = pd.DataFrame()

    def load_fingerprint_data(self, data_prefix="CHEMBL234_Ki_fp", prop_prefix="CHEMBL234_Ki_fp", data_dir="files"):
        """Load fingerprint and property arrays for all configured fingerprint types."""
        self.fingerprint_data = {}
        self.property_data = {}

        for fp_type in self.fingerprint_types:
            fps_file = f"{data_dir}/fps_{data_prefix}_{fp_type}.npy"
            props_file = f"{data_dir}/props_{prop_prefix}_{fp_type}.npy"

            try:
                self.fingerprint_data[fp_type] = np.load(fps_file)
                self.property_data[fp_type] = np.load(props_file)
                print(f"Loaded {fp_type}: {self.fingerprint_data[fp_type].shape[0]} molecules")
            except FileNotFoundError as exc:
                print(f"Warning: Could not load {fp_type} data - {exc}")

    def _fit_cliff_clusters(self, fps, props, threshold):
        bb_ac.activity_cliffs = True
        model = bb_ac.BitBirch(threshold=threshold)
        model.fit(fps, props)
        return model.get_cluster_mol_ids()

    def _fit_smooth_clusters(self, fps, props, threshold):
        bb_ac.activity_cliffs = False
        model = bb_ac.BitBirch(threshold=threshold)
        model.fit(fps, props)
        return model.get_cluster_mol_ids()

    def perform_clustering(self):
        """Run standard BitBIRCH cliff and smooth clustering."""
        self.cluster_data = defaultdict(dict)
        self.results = []

        for fp_type in self.fingerprint_types:
            if fp_type not in self.fingerprint_data:
                print(f"Skipping {fp_type} - data not loaded")
                continue

            fps = self.fingerprint_data[fp_type]
            props = self.property_data[fp_type]
            print(f"\nProcessing {fp_type} fingerprints...")

            for threshold in self.thresholds:
                print(f"  Threshold: {threshold}")
                cliff_ids = self._fit_cliff_clusters(fps, props, threshold)
                smooth_ids = self._fit_smooth_clusters(fps, props, threshold)

                key = f"{fp_type}_{threshold}"
                self.cluster_data[key] = {
                    "fingerprint_type": fp_type,
                    "threshold": threshold,
                    "cliff_ids": cliff_ids,
                    "smooth_ids": smooth_ids,
                    "properties": props,
                }

                print(f"    Cliff clusters: {len(cliff_ids)}")
                print(f"    Smooth clusters: {len(smooth_ids)}")

                for idx, (cliff_cluster, smooth_cluster) in enumerate(zip(cliff_ids[: self.top], smooth_ids[: self.top])):
                    cliff_props = props[cliff_cluster]
                    smooth_props = props[smooth_cluster]
                    self.results.append(
                        {
                            "fingerprint_type": fp_type,
                            "threshold": threshold,
                            "cluster_index": idx,
                            "cliff_nmols": len(cliff_cluster),
                            "smooth_nmols": len(smooth_cluster),
                            "cliff_p_mean": float(np.mean(cliff_props)),
                            "cliff_p_std": float(np.std(cliff_props)),
                            "smooth_p_mean": float(np.mean(smooth_props)),
                            "smooth_p_std": float(np.std(smooth_props)),
                        }
                    )

        self.df_results = pd.DataFrame(self.results)

    def perform_exhaustive_posthoc_smooth_clustering(self, property_span=1.0, top_subclusters=20):
        """Generate smooth clusters post hoc from cliff clusters.

        Each cliff cluster is sorted by property and greedily partitioned into
        subclusters whose property span is <= property_span.
        The selected top_subclusters are stored as smooth_ids for visualization.
        """
        self.cluster_data = defaultdict(dict)
        self.results = []

        for fp_type in self.fingerprint_types:
            if fp_type not in self.fingerprint_data:
                print(f"Skipping {fp_type} - data not loaded")
                continue

            fps = self.fingerprint_data[fp_type]
            props = self.property_data[fp_type]
            print(f"\nProcessing {fp_type} fingerprints (post-hoc smooth)...")

            for threshold in self.thresholds:
                print(f"  Threshold: {threshold}")
                cliff_ids = self._fit_cliff_clusters(fps, props, threshold)
                all_clusters = sorted(cliff_ids, key=len, reverse=True)

                threshold_subclusters = []
                for cluster_rank, cluster in enumerate(all_clusters, 1):
                    mol_ids = list(cluster)
                    cluster_props = props[mol_ids]

                    order = np.argsort(cluster_props)
                    sorted_ids = [mol_ids[i] for i in order]
                    sorted_props = cluster_props[order]

                    left = 0
                    sub_idx = 0
                    n = len(sorted_props)
                    while left < n:
                        right = left
                        while right + 1 < n and (sorted_props[right + 1] - sorted_props[left] <= property_span):
                            right += 1

                        sub_props = sorted_props[left : right + 1]
                        threshold_subclusters.append(
                            {
                                "threshold": threshold,
                                "fingerprint_type": fp_type,
                                "cluster_rank": cluster_rank,
                                "cluster_size": n,
                                "subcluster_idx": sub_idx,
                                "subcluster_size": right - left + 1,
                                "prop_min": float(sub_props[0]),
                                "prop_max": float(sub_props[-1]),
                                "prop_range": float(sub_props[-1] - sub_props[0]),
                                "prop_std": float(np.std(sub_props)),
                                "mol_ids": sorted_ids[left : right + 1],
                            }
                        )

                        sub_idx += 1
                        left = right + 1

                selected_subclusters = sorted(
                    threshold_subclusters,
                    key=lambda x: (x["subcluster_size"], x["prop_std"]),
                    reverse=True,
                )[:top_subclusters]

                smooth_ids = [sub["mol_ids"] for sub in selected_subclusters]
                key = f"{fp_type}_{threshold}"
                self.cluster_data[key] = {
                    "fingerprint_type": fp_type,
                    "threshold": threshold,
                    "cliff_ids": cliff_ids,
                    "smooth_ids": smooth_ids,
                    "properties": props,
                    "posthoc_top_subclusters": selected_subclusters,
                }

                print(f"    Cliff clusters: {len(cliff_ids)}")
                print(f"    Post-hoc smooth subclusters kept: {len(smooth_ids)}")

                for idx, sub in enumerate(selected_subclusters):
                    cliff_cluster = cliff_ids[idx] if idx < len(cliff_ids) else []
                    cliff_props = props[cliff_cluster] if len(cliff_cluster) else np.array([])
                    smooth_props = props[sub["mol_ids"]]
                    self.results.append(
                        {
                            "fingerprint_type": fp_type,
                            "threshold": threshold,
                            "cluster_index": idx,
                            "cliff_nmols": int(len(cliff_cluster)) if len(cliff_cluster) else np.nan,
                            "smooth_nmols": int(sub["subcluster_size"]),
                            "cliff_p_mean": float(np.mean(cliff_props)) if len(cliff_props) else np.nan,
                            "cliff_p_std": float(np.std(cliff_props)) if len(cliff_props) else np.nan,
                            "smooth_p_mean": float(np.mean(smooth_props)),
                            "smooth_p_std": float(sub["prop_std"]),
                            "smooth_parent_cluster_rank": int(sub["cluster_rank"]),
                            "smooth_prop_range": float(sub["prop_range"]),
                        }
                    )

        self.df_results = pd.DataFrame(self.results)

    # ------------------------------------------------------------------
    def perform_maximal_smooth_interval_clustering(
        self,
        property_span: float = 1.0,
        top_n: int = 20,
    ):
        """Find the maximal contiguous smooth interval inside each cliff cluster.

        For every cliff cluster the molecules are sorted by property value and a
        two-pointer sliding window identifies the **longest** subarray where
        ``max - min <= property_span``.  Unlike
        ``perform_exhaustive_posthoc_smooth_clustering``, which greedily
        partitions the full cluster into non-overlapping windows, this method
        picks the single best (largest) window per cluster.

        The ``top_n`` clusters ranked by size are examined and their results are
        stored in ``self.cluster_data[key]['smooth_ids']`` so that
        ``visualize_molecules`` works without modification.

        Per-cluster statistics recorded
        --------------------------------
        cluster_size    : total molecules in the cliff cluster
        cluster_std     : std of all property values in the cliff cluster
        smooth_interval : number of molecules in the maximal smooth window
        smooth_std      : std of the property values inside that window
        interval_min    : lowest property value in the window
        interval_max    : highest property value in the window
        interval_range  : interval_max - interval_min

        Parameters
        ----------
        property_span : float
            Maximum allowed ``max - min`` within a smooth interval (default 1.0).
        top_n : int
            Number of largest cliff clusters to process (default 20).
        """
        self.cluster_data = defaultdict(dict)
        self.results = []

        for fp_type in self.fingerprint_types:
            if fp_type not in self.fingerprint_data:
                print(f"Skipping {fp_type} - data not loaded")
                continue

            fps   = self.fingerprint_data[fp_type]
            props = self.property_data[fp_type]
            print(f"\nProcessing {fp_type} fingerprints (maximal smooth interval)...")

            for threshold in self.thresholds:
                print(f"  Threshold: {threshold}")
                print(
                    f"  {'Rank':<6} {'Cluster Size':<15} "
                    f"{'Cluster Std':<15} {'Smooth Interval':<18} "
                    f"{'Smooth Std':<12} {'Property Range'}"
                )
                print("  " + "-" * 80)

                cliff_ids = self._fit_cliff_clusters(fps, props, threshold)
                top_clusters = sorted(cliff_ids, key=len, reverse=True)[:top_n]

                smooth_ids = []  # list of mol-id lists, one per processed cluster

                for rank, cluster in enumerate(top_clusters, 1):
                    mol_ids      = list(cluster)
                    cluster_props = props[mol_ids]

                    # Sort by property value
                    order         = np.argsort(cluster_props)
                    sorted_ids    = [mol_ids[i] for i in order]
                    sorted_props  = cluster_props[order]

                    cluster_std = float(np.std(cluster_props))

                    # Two-pointer sliding window: longest window with
                    # sorted_props[r] - sorted_props[l] <= property_span
                    best_len, best_l = 1, 0
                    l = 0
                    for r in range(len(sorted_props)):
                        while sorted_props[r] - sorted_props[l] > property_span:
                            l += 1
                        if r - l + 1 > best_len:
                            best_len = r - l + 1
                            best_l   = l

                    interval_ids   = sorted_ids[best_l : best_l + best_len]
                    interval       = sorted_props[best_l : best_l + best_len]
                    smooth_std     = float(np.std(interval))
                    interval_range = float(interval[-1] - interval[0])

                    smooth_ids.append(interval_ids)

                    print(
                        f"  {rank:<6} {len(cluster):<15} {cluster_std:<15.3f} "
                        f"{best_len:<18} {smooth_std:<12.3f} "
                        f"[{interval[0]:.3f}, {interval[-1]:.3f}]  "
                        f"(range={interval_range:.3f})"
                    )

                    self.results.append(
                        {
                            "fingerprint_type": fp_type,
                            "threshold":        threshold,
                            "rank":             rank,
                            "cluster_size":     len(cluster),
                            "cluster_std":      cluster_std,
                            "smooth_interval":  best_len,
                            "smooth_std":       smooth_std,
                            "interval_min":     float(interval[0]),
                            "interval_max":     float(interval[-1]),
                            "interval_range":   interval_range,
                        }
                    )

                key = f"{fp_type}_{threshold}"
                self.cluster_data[key] = {
                    "fingerprint_type": fp_type,
                    "threshold":        threshold,
                    "cliff_ids":        cliff_ids,
                    "smooth_ids":       smooth_ids,
                    "properties":       props,
                }

                print(f"  Cliff clusters : {len(cliff_ids)}")
                print(f"  Top-{top_n} processed, smooth intervals stored: {len(smooth_ids)}")

        self.df_results = pd.DataFrame(self.results)

    # ------------------------------------------------------------------
    def get_cluster_statistics(self):
        """Print and return a DataFrame of total / singleton cluster counts.

        Reports statistics for every (fingerprint_type, threshold) combination
        currently stored in ``self.cluster_data``.  Mirrors the inline stats
        block from the original notebook exploration::

            Total Clusters | Singleton Clusters | Fraction Singleton

        Returns
        -------
        pd.DataFrame with columns:
            fingerprint_type, threshold, total_clusters,
            singleton_clusters, fraction_singleton
        """
        rows = []
        print("\nCluster Statistics by Fingerprint Type and Threshold:")
        print(
            f"{'FP Type':<10} {'Threshold':<12} {'Total':<15} "
            f"{'Singletons':<20} {'Fraction Singleton'}"
        )
        print("-" * 70)

        for key, data in sorted(self.cluster_data.items()):
            fp_type   = data["fingerprint_type"]
            threshold = data["threshold"]
            cliff_ids = data["cliff_ids"]

            total     = len(cliff_ids)
            singletons = sum(1 for c in cliff_ids if len(c) == 1)
            fraction  = singletons / total if total > 0 else 0.0

            print(
                f"{fp_type:<10} {threshold:<12.2f} {total:<15} "
                f"{singletons:<20} {fraction:<20.4f}"
            )
            rows.append(
                {
                    "fingerprint_type":   fp_type,
                    "threshold":          threshold,
                    "total_clusters":     total,
                    "singleton_clusters": singletons,
                    "fraction_singleton": fraction,
                }
            )

        return pd.DataFrame(rows)

    def plot_cluster_size_distribution(self, fp_type: str = None, save_path: str = None, dpi: int = 600):
        """Plot the distribution of cluster sizes for each threshold.

        Parameters
        ----------
        fp_type   : str, optional
            Filter to a single fingerprint type.  Defaults to the first
            available type.
        save_path : str, optional
            File path for saving the figure.  If None the figure is not saved.
        dpi       : int
            Resolution for saved figure (default 600).
        """
        if self.df_results.empty:
            print("No results found. Run a clustering method first.")
            return

        df = self.df_results

        if "cluster_std" in df.columns:
            # from perform_maximal_smooth_interval_clustering
            col_cliff_std  = "cluster_std"
            col_smooth_std = "smooth_std"
            col_rank       = "rank"
        elif "cliff_p_std" in df.columns and "smooth_p_std" in df.columns:
            # from perform_exhaustive_posthoc_smooth_clustering
            col_cliff_std  = "cliff_p_std"
            col_smooth_std = "smooth_p_std"
            col_rank       = "cluster_index"
        else:
            print("Required columns for plotting not present.")
            return

        if fp_type is None:
            fp_type = df["fingerprint_type"].iloc[0]

        df = df[df["fingerprint_type"] == fp_type]
        thresholds = sorted(df["threshold"].unique())
        colors     = plt.cm.viridis(np.linspace(0, 1, len(thresholds)))

        fig, ax = plt.subplots(figsize=(10, 6))

        for threshold, color in zip(thresholds, colors):
            sub = df[df["threshold"] == threshold].sort_values(col_rank)
            
            # Filter out NaNs if any (e.g. from subclusters with no parent cliff cluster stats)
            sub = sub.dropna(subset=[col_cliff_std, col_smooth_std])
            
            ax.plot(sub[col_rank], sub[col_cliff_std],
                    color=color, linestyle="-", linewidth=1.5,
                    marker="o", markersize=4,
                    label=f"Cluster std  th={threshold:.2f}")
            ax.plot(sub[col_rank], sub[col_smooth_std],
                    color=color, linestyle="--", linewidth=1.5,
                    marker="o", markersize=4,
                    label=f"Smooth std   th={threshold:.2f}")

        ax.set_xlabel("Cluster Rank" if col_rank == "rank" else "Subcluster Index")
        ax.set_ylabel("Property Std")
        ax.set_title(f"{fp_type}: Cluster Std vs Smooth Interval Std")
        ax.set_xticks(df[col_rank].unique())
        ax.legend(
            loc="upper left", bbox_to_anchor=(1.01, 1),
            fontsize=7.5, borderaxespad=0, frameon=True,
        )
        plt.tight_layout()

        if save_path:
            plt.savefig(save_path, dpi=dpi, bbox_inches="tight")
            print(f"Plot saved → {save_path}")

        plt.show()
    # ------------------------------------------------------------------
    def plot_smooth_interval_results(
        self,
        fp_type: str = None,
        save_path: str = None,
        dpi: int = 600,
    ):
        """Plot cluster_std vs smooth_std across ranks for each threshold.

        Solid lines show the full-cluster property std; dashed lines show the
        std inside the smooth interval/subcluster.

        Parameters
        ----------
        fp_type   : str, optional
            Filter to a single fingerprint type.  Defaults to the first
            available type.
        save_path : str, optional
            File path for saving the figure.  If None the figure is not saved.
        dpi       : int
            Resolution for saved figure (default 600).
        """
        if self.df_results.empty:
            print("No results found. Run a clustering method first.")
            return

        df = self.df_results

        if "cluster_std" in df.columns:
            # from perform_maximal_smooth_interval_clustering
            col_cliff_std  = "cluster_std"
            col_smooth_std = "smooth_std"
            col_rank       = "rank"
        elif "cliff_p_std" in df.columns and "smooth_p_std" in df.columns:
            # from perform_exhaustive_posthoc_smooth_clustering
            col_cliff_std  = "cliff_p_std"
            col_smooth_std = "smooth_p_std"
            col_rank       = "cluster_index"
        else:
            print("Required columns for plotting not present.")
            return

        if fp_type is None:
            fp_type = df["fingerprint_type"].iloc[0]

        df = df[df["fingerprint_type"] == fp_type]
        thresholds = sorted(df["threshold"].unique())
        colors     = plt.cm.viridis(np.linspace(0, 1, len(thresholds)))

        fig, ax = plt.subplots(figsize=(10, 6))

        for threshold, color in zip(thresholds, colors):
            sub = df[df["threshold"] == threshold].sort_values(col_rank)
            
            # Filter out NaNs if any (e.g. from subclusters with no parent cliff cluster stats)
            sub = sub.dropna(subset=[col_cliff_std, col_smooth_std])
            
            ax.plot(sub[col_rank], sub[col_cliff_std],
                    color=color, linestyle="-", linewidth=1.5,
                    marker="o", markersize=4,
                    label=f"Cluster std  th={threshold:.2f}")
            ax.plot(sub[col_rank], sub[col_smooth_std],
                    color=color, linestyle="--", linewidth=1.5,
                    marker="o", markersize=4,
                    label=f"Smooth std   th={threshold:.2f}")

        ax.set_xlabel("Cluster Rank" if col_rank == "rank" else "Subcluster Index")
        ax.set_ylabel("Property Std")
        ax.set_title(f"{fp_type}: Cluster Std vs Smooth Interval Std")
        ax.set_xticks(df[col_rank].unique())
        ax.legend(
            loc="upper left", bbox_to_anchor=(1.01, 1),
            fontsize=7.5, borderaxespad=0, frameon=True,
        )
        plt.tight_layout()

        if save_path:
            plt.savefig(save_path, dpi=dpi, bbox_inches="tight")
            print(f"Plot saved → {save_path}")

        plt.show()

    def get_available_fingerprint_configs(self):
        return list(self.cluster_data.keys())

    def visualize_molecules(

        self,
        fingerprint_type,
        threshold,
        cluster_index,
        smiles_file,
        max_molecules=20,
        save_images=True,
        show_images=True,
        smiles_col="smiles",
        prop_col="exp_mean [nM]",
    ):
        """Visualize cliff and smooth clusters for one config and cluster index."""
        key = f"{fingerprint_type}_{threshold}"
        if key not in self.cluster_data:
            print(f"Error: No clustering data for {fingerprint_type} at threshold {threshold}")
            return None

        cluster_info = self.cluster_data[key]
        cliff_ids = cluster_info["cliff_ids"]
        smooth_ids = cluster_info["smooth_ids"]

        if cluster_index >= len(cliff_ids) or cluster_index >= len(smooth_ids):
            print("Error: cluster_index is out of range")
            print(f"Available cliff clusters: {len(cliff_ids)}")
            print(f"Available smooth clusters: {len(smooth_ids)}")
            return None

        df_smiles = pd.read_csv(smiles_file)
        cliff_cluster_indices = cliff_ids[cluster_index][:max_molecules]
        smooth_cluster_indices = smooth_ids[cluster_index][:max_molecules]

        cliff_results = self._process_cluster_molecules(df_smiles, cliff_cluster_indices, smiles_col, prop_col)
        smooth_results = self._process_cluster_molecules(df_smiles, smooth_cluster_indices, smiles_col, prop_col)

        if show_images and cliff_results["molecules"]:
            self._create_cluster_visualization(cliff_results, "Cliff", fingerprint_type, threshold, cluster_index, save_images)

        if show_images and smooth_results["molecules"]:
            self._create_cluster_visualization(smooth_results, "Smooth", fingerprint_type, threshold, cluster_index, save_images)

        return {
            "cliff_results": cliff_results,
            "smooth_results": smooth_results,
            "fingerprint_type": fingerprint_type,
            "threshold": threshold,
            "cluster_index": cluster_index,
        }

    def _process_cluster_molecules(self, df_smiles, indices, smiles_col, prop_col):
        results = {
            "molecules": [],
            "properties": [],
            "smiles": [],
            "indices": list(indices),
            "valid_count": 0,
            "invalid_count": 0,
        }

        cluster_smiles = df_smiles.iloc[indices][smiles_col].tolist()
        cluster_props = df_smiles.iloc[indices][prop_col].tolist()

        for smile, prop in zip(cluster_smiles, cluster_props):
            mol = Chem.MolFromSmiles(smile)
            if mol is None:
                results["invalid_count"] += 1
                continue
            results["molecules"].append(mol)
            results["properties"].append(prop)
            results["smiles"].append(smile)
            results["valid_count"] += 1

        return results

    def _create_cluster_visualization(self, cluster_results, cluster_type, fp_type, threshold, cluster_idx, save_image):
        molecules = cluster_results["molecules"]
        properties = cluster_results["properties"]
        if not molecules:
            print(f"No valid molecules to visualize for {cluster_type} cluster")
            return

        legends = [f"{i + 1}. {p:.2f} nM" for i, p in enumerate(properties)]
        svg_result = Draw.MolsToGridImage(
            molecules,
            molsPerRow=4,
            subImgSize=(600, 600),
            legends=legends,
            useSVG=True,
        )

        svg_str = svg_result.data if hasattr(svg_result, "data") else str(svg_result)
        svg_str = _increase_svg_font_size(svg_str, scale_factor=2.5)
        display(SVG(svg_str))

        if save_image:
            os.makedirs("molecules", exist_ok=True)
            filename = f"molecules/{cluster_type.lower()}_cluster_{fp_type}_{threshold}_{cluster_idx}.svg"
            with open(filename, "w") as handle:
                handle.write(svg_str)
            print(f"Saved SVG image: {filename}")

    def save_results_to_csv(self, filename="clustering_results.csv"):
        if self.df_results.empty:
            print("No results to save. Run a clustering method first.")
            return None
        self.df_results.to_csv(filename, index=False)
        print(f"Results saved to {filename}")
        return self.df_results


def main():
    analyzer = FingerprintClusterAnalyzer(
        fingerprint_types=["ECFP", "MACCS", "RDKIT"],
        thresholds=np.round(np.arange(0.3, 1.0, 0.1), 1),
        top=10,
    )

    # ── Choose clustering mode ────────────────────────────────────────────────
    # "standard"         → perform_clustering (cliff + smooth BitBIRCH)
    # "posthoc_smooth"   → perform_exhaustive_posthoc_smooth_clustering
    # "maximal_interval" → perform_maximal_smooth_interval_clustering  ← new
    mode = "maximal_interval"

    property_span       = 1.0   # max - min threshold for smooth windows
    posthoc_top         = 20    # used by posthoc_smooth and maximal_interval

    print("Loading fingerprint data...")
    analyzer.load_fingerprint_data(
        data_prefix="CHEMBL234_Ki_fp",
        prop_prefix="CHEMBL234_Ki_fp",
        data_dir="files",
    )

    print("\nPerforming clustering...")
    if mode == "posthoc_smooth":
        analyzer.perform_exhaustive_posthoc_smooth_clustering(
            property_span=property_span,
            top_subclusters=posthoc_top,
        )
    elif mode == "maximal_interval":
        analyzer.perform_maximal_smooth_interval_clustering(
            property_span=property_span,
            top_n=posthoc_top,
        )
    else:
        analyzer.perform_clustering()

    # Print cluster statistics (total / singleton counts per threshold)
    df_stats = analyzer.get_cluster_statistics()

    analyzer.save_results_to_csv("clustering_results_simplified.csv")

    # Plot cluster std vs smooth std
    if mode in ["maximal_interval", "posthoc_smooth"]:
        analyzer.plot_smooth_interval_results(
            fp_type="ECFP",
            save_path="results/ECFP_prop_std_plot.png",
        )

    smiles_file = "data/CHEMBL234_Ki.csv"
    analyzer.visualize_molecules("ECFP", 0.9, 0, smiles_file, max_molecules=20)


if __name__ == "__main__":
    main()
